#!/bin/bash

info=$(acpi -b | sed -e "s/Battery 0: //" -e "s/,//g")
status=$(echo $info | awk '{print $1}')
percent=$(echo $info | awk '{print $2}' | sed -e "s/%//")
lefttime=$(echo $info | awk '{print $3}' | rev | cut -c 4- | rev)

text=''

if [ $status = "Discharging" ]; then
    if [ $percent -lt 25 ]; then
        text=" "
    elif [ $percent -lt 50 ]; then
        text=" "
    elif [ $percent -lt 75 ]; then
        text=" "
    else
        text=" "
    fi

    if [ $BLOCK_BUTTON -gt 0 ]; then
        echo "${text} ${lefttime}"
        echo "${text} ${lefttime}"
    else
        echo "${text} ${percent}"
        echo "${text} ${percent}"
    fi

    if [ $percent -lt 15 ]; then
        echo "#e06c75"
    elif [ $percent -lt 35 ]; then
        echo "#e5c07b"
    elif [ $percent -lt 55 ]; then
        echo "#c8ccd4"
    elif [ $percent -lt 75 ]; then
        echo "#c8ccd4"
    else
        echo "#98c379"
    fi

else
    text="  ${percent}"

    if [ $BLOCK_BUTTON -gt 0 ]; then
        echo $lefttime
        echo $lefttime
    else
        echo $text
        echo $text
    fi
    
    if [ $percent -gt 89 ]; then
        echo "#98c379"
    fi

fi
