#!/bin/bash

connected=$(echo info | bluetoothctl | grep 'Device' | wc -l)
status=$(bluetooth | awk '{ print $3 }')

case $BLOCK_BUTTON in
    1) blueman-manager ;;
    3) blueman-manager ;;
esac

echo "  "
echo "  "

if [ $status = "on" ]; then
    if [ $connected -eq 0 ]; then
        echo "#c8ccd4"
    else
	echo "#98c379"
    fi
else
    echo "#e06c75"
fi
